sudo: required
services:
  - docker
language: go
go:
  - 1.8
install: make fetch
script: docker run --rm -v $(pwd):/go/src/github.com/shyiko/kubesec:ro -w /go/src/github.com/shyiko/kubesec shyiko/kubesec-ci:latest /bin/bash -c "make test"
